availableSecrets:
  secretManager:
#    - versionName: projects/772190012442/secrets/APPLICATION/versions/latest
#      env: SECRET_ENV_LOCAL
    - versionName: projects/772190012442/secrets/APPLICATION-REMOTE/versions/latest
      env: SECRET_ENV_REMOTE
    - versionName: projects/772190012442/secrets/APPLICATION-AI/versions/latest
      env: SECRET_ENV_AI

steps:
#  # ðŸ”¹ 1. LOCAL ì„œë¹„ìŠ¤ìš© secret íŒŒì¼ ìƒì„± + ë¹Œë“œ + ë°°í¬
#  - name: 'ubuntu'
#    entrypoint: 'bash'
#    args:
#      - '-c'
#      - |
#        echo "$$SECRET_ENV_LOCAL" > src/main/resources/secret.yml
#        echo "$$SECRET_ENV_AI" > src/main/resources/gemini-ai-key.json
#    secretEnv: ['SECRET_ENV_LOCAL', 'SECRET_ENV_AI']
#
#  - name: gradle:8.5-jdk21
#    args: [ 'gradle','build' ]
#
#  - name: 'gcr.io/cloud-builders/docker'
#    args: ['build', '-t',
#           'asia-northeast3-docker.pkg.dev/gen-lang-client-0798322573/planpal-server/planpal-local',
#           '.']
#
#  - name: 'gcr.io/cloud-builders/docker'
#    args: ['push',
#           'asia-northeast3-docker.pkg.dev/gen-lang-client-0798322573/planpal-server/planpal-local']
#
#  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
#    entrypoint: gcloud
#    args:
#      [
#        "run", "deploy", "planpal-server-local",
#        "--image", "asia-northeast3-docker.pkg.dev/gen-lang-client-0798322573/planpal-server/planpal-local",
#        "--region", "asia-northeast3",
#        "--platform", "managed",
#        "--allow-unauthenticated",
#      ]

  # ðŸ”¹ 2. REMOTE ì„œë¹„ìŠ¤ìš© secret íŒŒì¼ ìƒì„± + ë¹Œë“œ + ë°°í¬
  - name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "$$SECRET_ENV_REMOTE" > src/main/resources/secret.yml
        echo "$$SECRET_ENV_AI" > src/main/resources/gemini-ai-key.json
    secretEnv: ['SECRET_ENV_REMOTE', 'SECRET_ENV_AI']

  - name: gradle:7.6-jdk17
    args: [ 'gradle','build' ]

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t',
           'asia-northeast3-docker.pkg.dev/gen-lang-client-0798322573/planpal-server/planpal-remote',
           '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push',
           'asia-northeast3-docker.pkg.dev/gen-lang-client-0798322573/planpal-server/planpal-remote']

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run", "deploy", "planpal-server-remote",
        "--image", "asia-northeast3-docker.pkg.dev/gen-lang-client-0798322573/planpal-server/planpal-remote",
        "--region", "asia-northeast3",
        "--platform", "managed",
        "--allow-unauthenticated",
      ]

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8

images:
#  - 'asia-northeast3-docker.pkg.dev/gen-lang-client-0798322573/planpal-server/planpal-local'
  - 'asia-northeast3-docker.pkg.dev/gen-lang-client-0798322573/planpal-server/planpal-remote'
